import React,{useEffect,useState} from 'react';
import type {Flight} from './flight';
import {calculateFuelPlan,defaultFuelPlan,fuelPlanSignature,fuelPlanReportHtml,fuelProfileSvg,fuelBreakdownSvg} from './fuel-planning';
import type {FuelLeg,FuelPhase,FuelPlanInput,FuelPlanResult} from './fuel-planning';

export interface FuelPlanningProps {
 flight:Flight;input:FuelPlanInput;onChange:(input:FuelPlanInput)=>void;
 onApplyFuel:(requiredRampKg:number)=>void;disabled?:boolean;
}
const n=(v:number|null|undefined)=>typeof v==='number'&&Number.isFinite(v)?v.toLocaleString('en-US',{maximumFractionDigits:1}):'—';
function Numeric({label,value,onChange,disabled=false}:{label:string;value:number;onChange:(value:number)=>void;disabled?:boolean}){return <label className="lf-field"><span>{label}</span><input aria-label={label} type="number" step="any" value={Number.isFinite(value)?value:''} disabled={disabled} onChange={e=>onChange(e.target.value===''?NaN:Number(e.target.value))}/></label>;}
function save(name:string,value:string|FuelPlanResult){const url=URL.createObjectURL(new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type:typeof value==='string'?'text/html;charset=utf-8':'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export function FuelPlanning({flight,input,onChange,onApplyFuel,disabled=false}:FuelPlanningProps){
 const [entry,setEntry]=useState<FuelPlanResult|null>(null),[message,setMessage]=useState('核对显式航段、阶段油耗与储备策略后执行计算。');
 const key=fuelPlanSignature(flight,input),result=!disabled&&entry?.signature===key?entry:null;
 const mismatch=input.airports.from!==flight.from||input.airports.to!==flight.to||input.airports.alternate!==flight.alternate||input.route!==flight.route;
 const set=(next:FuelPlanInput)=>{onChange(next);setMessage('输入已修改，旧预算与采用操作已失效，请重新计算。');};
 const compute=()=>{if(disabled)return;const value=calculateFuelPlan(flight,input);setEntry(value);setMessage(value.label);};
 const status=result?.status||(entry?'stale':'not-calculated');
 const updateLeg=(group:'routeLegs'|'alternateLegs',index:number,patch:Partial<FuelLeg>)=>set({...input,[group]:input[group].map((leg,i)=>i===index?{...leg,...patch}:leg)});
 const updatePhase=(group:'climb'|'descent'|'missedApproach'|'alternateDescent',patch:Partial<FuelPhase>)=>set({...input,[group]:{...input[group],...patch}});
 const updatePolicy=(patch:Partial<FuelPlanInput['policy']>)=>set({...input,policy:{...input.policy,...patch}});
 const apply=()=>{if(!result?.canApply||result.requiredRampKg===null)return;try{onApplyFuel(result.requiredRampKg);setMessage('已请求采用建议停机坪燃油。请重新确认航班重量，并重算相关性能。');}catch(e){setMessage((e as Error).message);}};
 useEffect(()=>{
  const api={snapshot:()=>({status,valid:result?.status==='engineering-feasible',canApply:!!result?.canApply,result:result?structuredClone(result):null}),report:()=>{if(!result)throw Error('燃油结果已失效，请重新计算');return fuelPlanReportHtml(result);}};
  (window as any).__FUEL_PLANNING__=api;return()=>{if((window as any).__FUEL_PLANNING__===api)delete (window as any).__FUEL_PLANNING__;};
 });
 const legEditor=(group:'routeLegs'|'alternateLegs',title:string)=><section><h3>{title}</h3><p className="lf-muted">以下距离仅含巡航航段，爬升、复飞和下降距离在阶段表单另计。迎风为正，顺风为负。</p>{input[group].map((leg,index)=><div key={leg.id} style={{borderTop:'1px solid #364557',paddingTop:12,marginTop:12}}>
  <div className="lf-toolbar"><b>{index+1}.</b><label className="lf-field"><span>航段名称</span><input aria-label={`${title}${index+1}名称`} value={leg.label} disabled={disabled} onChange={e=>updateLeg(group,index,{label:e.target.value})}/></label><button disabled={disabled||input[group].length<=1} onClick={()=>set({...input,[group]:input[group].filter((_,i)=>i!==index)})}>删除{title}{index+1}</button></div>
  <div className="lf-grid"><Numeric label={`${title}${index+1}距离 (NM)`} value={leg.distanceNm} disabled={disabled} onChange={distanceNm=>updateLeg(group,index,{distanceNm})}/><Numeric label={`${title}${index+1}真空速 TAS (kt)`} value={leg.tasKt} disabled={disabled} onChange={tasKt=>updateLeg(group,index,{tasKt})}/><Numeric label={`${title}${index+1}迎风 (kt)`} value={leg.headwindKt} disabled={disabled} onChange={headwindKt=>updateLeg(group,index,{headwindKt})}/><Numeric label={`${title}${index+1}油耗率 (kg/h)`} value={leg.fuelFlowKgPerHour} disabled={disabled} onChange={fuelFlowKgPerHour=>updateLeg(group,index,{fuelFlowKgPerHour})}/></div>
  <label className="lf-field" style={{marginTop:8}}><span>数据来源 / 工程假设</span><input aria-label={`${title}${index+1}来源`} value={leg.source} disabled={disabled} onChange={e=>updateLeg(group,index,{source:e.target.value})}/></label>
 </div>)}<button style={{marginTop:12}} disabled={disabled||input[group].length>=50} onClick={()=>set({...input,[group]:[...input[group],{id:group+'-'+Date.now()+'-'+input[group].length,label:'新增手工航段',distanceNm:100,tasKt:group==='routeLegs'?450:250,headwindKt:0,fuelFlowKgPerHour:5000,source:'用户手工工程假设；待核对'}]})}>添加{title}</button></section>;
 const phaseEditor=(group:'climb'|'descent'|'missedApproach'|'alternateDescent',label:string)=><section><h3>{label}</h3><div className="lf-grid"><Numeric label={`${label}时间 (min)`} value={input[group].minutes} disabled={disabled} onChange={minutes=>updatePhase(group,{minutes})}/><Numeric label={`${label}距离 (NM)`} value={input[group].distanceNm} disabled={disabled} onChange={distanceNm=>updatePhase(group,{distanceNm})}/><Numeric label={`${label}油耗率 (kg/h)`} value={input[group].fuelFlowKgPerHour} disabled={disabled} onChange={fuelFlowKgPerHour=>updatePhase(group,{fuelFlowKgPerHour})}/></div><label className="lf-field" style={{marginTop:8}}><span>阶段来源</span><input aria-label={`${label}来源`} value={input[group].source} disabled={disabled} onChange={e=>updatePhase(group,{source:e.target.value})}/></label></section>;
 return <div data-testid="fuel-planning">
  <div className="lf-warning"><b>航路与备降燃油 · 工程预算模型</b><p>显式手工距离、定值油耗与可配置储备。输入与默认样例未经 A330 油耗校准；不解析航路文字，不进行法规放行判定。</p></div>
  <section style={{marginTop:16}}><h3>规划关联与资料来源</h3><p>本规划：{input.airports.from} → {input.airports.to} / 备降 {input.airports.alternate}；当前航班：{flight.from} → {flight.to} / 备降 {flight.alternate||'未填写'}</p><p>关联航路：{input.route}</p><label className="lf-field"><span>规划来源</span><input aria-label="燃油规划来源" value={input.source} disabled={disabled} onChange={e=>set({...input,source:e.target.value})}/></label>{mismatch&&<div className="lf-error"><p>机场或航路已改变，本规划不能继续采用。请先核对所有距离、阶段和来源，再明确关联当前航班。</p><button disabled={disabled||!flight.alternate} onClick={()=>set({...input,airports:{from:flight.from,to:flight.to,alternate:flight.alternate},route:flight.route})}>已复核手工航段，关联当前机场与航路</button></div>}<div className="lf-toolbar"><button disabled={disabled} onClick={()=>set(defaultFuelPlan(flight))}>载入手工演示样例</button><span className="lf-muted">样例数值不随机场自动查库；更换机场后须人工复核。</span></div></section>
  <div className="lf-cols" style={{marginTop:16}}>{legEditor('routeLegs','主航路航段')}{legEditor('alternateLegs','备降航段')}</div>
  <details style={{marginTop:16}}><summary style={{cursor:'pointer',padding:'10px 0'}}>爬升、下降及复飞阶段参数</summary><div className="lf-cols">{phaseEditor('climb','起飞及爬升')}{phaseEditor('descent','目的地下降')}{phaseEditor('missedApproach','复飞及备降爬升')}{phaseEditor('alternateDescent','备降下降')}</div><div className="lf-grid" style={{marginTop:12}}><Numeric label="主航路示意巡航高度 (ft)" value={input.cruiseAltitudeFt} disabled={disabled} onChange={cruiseAltitudeFt=>set({...input,cruiseAltitudeFt})}/><Numeric label="备降示意巡航高度 (ft)" value={input.alternateAltitudeFt} disabled={disabled} onChange={alternateAltitudeFt=>set({...input,alternateAltitudeFt})}/></div><p className="lf-muted">高度仅用于剖面示意；油耗仍按明确输入的阶段时间与油耗率计算。</p></details>
  <section style={{marginTop:16}}><h3>工程储备策略</h3><div className="lf-grid"><Numeric label="应急燃油比例 (%)" value={input.policy.contingencyPercent} disabled={disabled} onChange={contingencyPercent=>updatePolicy({contingencyPercent})}/><Numeric label="应急燃油最低量 (kg)" value={input.policy.contingencyMinimumKg} disabled={disabled} onChange={contingencyMinimumKg=>updatePolicy({contingencyMinimumKg})}/><Numeric label="最终储备等待时间 (min)" value={input.policy.holdingMinutes} disabled={disabled} onChange={holdingMinutes=>updatePolicy({holdingMinutes})}/><Numeric label="最终储备等待油耗率 (kg/h)" value={input.policy.holdingFlowKgPerHour} disabled={disabled} onChange={holdingFlowKgPerHour=>updatePolicy({holdingFlowKgPerHour})}/><Numeric label="额外燃油 (kg)" value={input.policy.extraKg} disabled={disabled} onChange={extraKg=>updatePolicy({extraKg})}/><div className="lf-field"><span>滑行燃油（来自当前航班）</span><strong>{n(flight.taxiKg)} kg</strong><small>在航班工作台修改，避免重复采用。</small></div></div><label className="lf-field" style={{marginTop:10}}><span>储备策略说明</span><input aria-label="储备策略说明" value={input.policy.source} disabled={disabled} onChange={e=>updatePolicy({source:e.target.value})}/></label></section>
  <div className="lf-toolbar"><button className="primary" disabled={disabled} onClick={compute}>计算航路燃油</button><button disabled={!result?.canApply} onClick={apply}>采用建议停机坪燃油</button><button disabled={!result} onClick={()=>result&&save('a330efb-fuel-plan.json',result)}>导出燃油结果 JSON</button><button disabled={!result} onClick={()=>result&&save('a330efb-fuel-report.html',fuelPlanReportHtml(result))}>导出燃油报告 HTML</button></div>
  <div className="lf-message" role="status">{disabled?'当前航班不可编辑，请先处理冲突或输入问题。':message}</div>
  <div data-testid="fuel-plan-result" data-status={status} data-valid={result?.status==='engineering-feasible'?'true':'false'} style={{marginTop:16}}>
   {!result?<p>{entry?'输入或计划已变化，旧燃油结果已撤销。':'尚未计算燃油预算。'}</p>:<><h3>{result.label}</h3>{result.errors.length>0&&<div className="lf-error">{result.errors.join('；')}</div>}{result.totals&&<><div className="lf-metrics"><div>当前停机坪燃油<strong>{n(flight.rampKg)}<small> kg</small></strong></div><div>建议停机坪燃油<strong>{n(result.requiredRampKg)}<small> kg</small></strong></div><div>计划减建议<strong>{n(result.plannedMarginKg)}<small> kg</small></strong></div><div>主航程时间<strong>{n(result.totals.tripMinutes)}<small> min</small></strong></div></div>
    <figure data-testid="fuel-profile" style={{margin:'16px 0',padding:12,border:'1px solid #415063',borderRadius:6}}><div dangerouslySetInnerHTML={{__html:fuelProfileSvg(result)}}/><div dangerouslySetInnerHTML={{__html:fuelBreakdownSvg(result)}}/><figcaption className="lf-muted">剖面横轴来自录入的累计航段距离；主航路和备降在目的地分开。比例条使用本次实际计算值。</figcaption></figure>
    <div className="lf-cols">{(['planned','required'] as const).map(kind=>{const m=result[kind]!;return <section key={kind}><h3>{kind==='planned'?'当前计划':'建议燃油采用后'}的名义状态</h3><p>起飞质量 {n(m.takeoffMassKg)} kg</p><p>目的地燃油账 {n(m.destinationLandingFuelKg)} kg；着陆质量 {m.destinationLandingFuelKg>=0?n(m.destinationLandingMassKg)+' kg':'不可达'}</p><p>备降燃油账 {n(m.alternateLandingFuelKg)} kg；着陆质量 {m.alternateLandingFuelKg>=0?n(m.alternateLandingMassKg)+' kg':'不可达'}</p><p>目的地备降＋最终储备余量 {n(m.destinationReserveMarginKg)} kg<br/>备降最终储备余量 {n(m.alternateReserveMarginKg)} kg</p>{result.checks.filter(c=>c.case===kind).map(c=><p key={c.id} style={{color:c.passed?'#8fdcc5':'#ffb3a4'}}>{c.passed?'✓':'✕'} {c.label}：{n(c.actual)} / {n(c.limit)} kg</p>)}</section>;})}</div>
   </>}<details style={{marginTop:14}}><summary>假设、来源与完整快照</summary>{[...result.warnings,...result.model.assumptions].map((v,i)=><p key={i}>{v}</p>)}{result.model.sources.map(s=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a>：{s.use}</p>)}<pre style={{fontSize:12,whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(result,null,2)}</pre></details></>}
  </div>
 </div>;
}
