import React,{useState} from 'react';
import {useHistory} from 'react-router-dom';
import {Flight,weights,validate,signature,profile,massConvert,lengthConvert,pressureConvert,example} from './flight';
import {useLocal,editFlight,confirmFlight,runCalculation,currentResult,archiveResult,restoreHistory,loadFlight,loadDraft,download,reportHtml,printReport,notice,readFuelTarget,adoptLatest,exportRecovery} from './state';
import {flightFile,parseFlightFile} from './flight-file';
import {EngineeringTakeoff} from './EngineeringTakeoff';
import {editDepartureInput,reviewManualWeather,reviewDepartureRunway} from './departure-review';
import {useRuntime,GroundPreparation,CommandReceipt} from './SimulationPages';
import './local.css';
const n=(v:number,d=1)=>Number.isFinite(v)?Number(v.toFixed(d)).toLocaleString('en-US'):'—';
const Field=({label,value,onChange,readOnly=false,type='number',name}:{label:string;value:any;onChange?:(s:string)=>void;readOnly?:boolean;type?:string;name:string})=><label className="lf-field"><span>{label}</span><input aria-label={label} data-field={name} type={type} step="any" value={typeof value==='number'&&!Number.isFinite(value)?'':value} readOnly={readOnly} onChange={e=>onChange?.(e.target.value)} /></label>;
const perform=(fn:()=>any)=>{try{fn();}catch(e){notice(String((e as Error).message));}};
function StorageActions(){const s=useLocal();return <>{s.storageConflict&&<div className="lf-error" role="alert">{s.notice}<button onClick={()=>perform(adoptLatest)}>读取最新版本</button><button onClick={()=>perform(()=>download('a330efb-local-draft.json',flightFile(s.flight,true)))}>导出本窗口草稿</button></div>}{s.hasRecovery&&<button onClick={()=>perform(exportRecovery)}>导出恢复备份</button>}</>;}
const Scope=()=> <div className="lf-warning"><b>数据包 {profile.profileVersion} · 参考模型，尚未完成航空性能校准</b><p>可算：重量一致性、结构重量约束、V2 源码表插值、压力高度、风分量和距离扣减。</p><p>未支持：V1 / VR / FLEX、跑道限制重量、起飞与加速停止距离、单发爬升、障碍物、刹车能量和轮胎限制。天气、标高、坡度不用于修正 V2；不输出“可起飞”结论。</p></div>;
function WeightCards({f}:{f:Flight}){const w=weights(f);return <div className="lf-metrics"><div>OEW <strong>{n(f.oewKg)}<small> kg</small></strong></div><div>载荷 <strong>{n(w.payload)}<small> kg</small></strong></div><div>ZFW <strong>{n(w.zfw)}<small> kg</small></strong></div><div>起飞重量 TOW <strong>{n(w.tow)}<small> kg</small></strong></div></div>;}
export function LocalFlightPage(){
 const s=useLocal(),f=s.flight,h=useHistory();const [unit,setUnit]=useState<'kg'|'lb'>('kg');
 const set=(key:string,v:any)=>editFlight({...f,[key]:v,source:'local-manual'});
 const massField=(key:keyof Flight,label:string,ro=false)=><Field key={key} name={key} label={label+' ('+unit+')'} value={Number(massConvert(f[key] as number,'kg',unit).toFixed(2))} readOnly={ro} onChange={v=>set(key,massConvert(v===''?NaN:Number(v),unit,'kg'))}/>;
 const errors=validate(f);
 return <div className="lf-root"><div className="lf-heading"><div><h2>本地航班工作台</h2><p>手工录入 / JSON 文件 · 核心流程无需账号或外网</p></div><span className="lf-chip">A330-941 · Trent 7000</span></div>
 <div className="lf-toolbar"><button onClick={()=>perform(()=>{editFlight({...example(),id:'LOCAL-'+Date.now(),number:'LOCAL330',source:'local-manual'});})}>新建航班</button><button onClick={()=>perform(()=>download('local-flight.json',flightFile(f)))}>导出航班 JSON</button><button onClick={()=>perform(()=>download('a330efb-local-draft.json',flightFile(f,true)))}>导出未确认草稿</button><label className="lf-file">导入航班 / 草稿 JSON<input aria-label="导入航班 JSON" type="file" accept=".json,application/json" onChange={async e=>{try{const file=e.target.files?.[0];if(file){if(file.size>524288)throw Error('航班文件超过 512 KiB');const input=parseFlightFile(await file.text());if(input.kind==='draft')loadDraft(input.flight);else loadFlight(input.flight);}}catch(err){notice('导入失败，保留原航班：'+String((err as Error).message));}e.target.value='';}}/></label><button className="primary" onClick={()=>confirmFlight()}>保存并确认重量</button><button onClick={()=>h.push('/performance/engineering-takeoff')}>进入工程起飞计算 →</button><button onClick={()=>h.push('/performance/local-takeoff')}>进入离线起飞核算 →</button></div>
 <div className="lf-message" role="status">{s.storageError||s.notice}</div><StorageActions/><WeightCards f={f}/>
 <div className="lf-cols"><section><h3>航班信息</h3><div className="lf-grid"><Field name="number" label="航班号" type="text" value={f.number} onChange={v=>set('number',v)}/><Field name="date" label="日期 (UTC)" type="date" value={f.date} onChange={v=>set('date',v)}/><Field name="from" label="起飞机场 ICAO" type="text" value={f.from} onChange={v=>set('from',v.toUpperCase())}/><Field name="to" label="目的机场 ICAO" type="text" value={f.to} onChange={v=>set('to',v.toUpperCase())}/><Field name="alternate" label="备降机场 ICAO" type="text" value={f.alternate} onChange={v=>set('alternate',v.toUpperCase())}/><Field name="route" label="航路文字（手工）" type="text" value={f.route} onChange={v=>set('route',v)}/></div><p className="lf-muted">航班标识：{f.id}。保存确认后，同一计划同步至原仪表盘、签派资料及燃油/载重目标。计划与本地模拟当前状态不会被称为真实飞机数据。</p></section>
 <section><h3>载荷与燃油 <select aria-label="重量显示单位" value={unit} onChange={e=>setUnit(e.target.value as any)}><option>kg</option><option>lb</option></select></h3><div className="lf-grid">{massField('oewKg','运行空重 OEW',true)}<Field name="pax" label="旅客人数" value={f.pax} onChange={v=>set('pax',v===''?NaN:Number(v))}/>{massField('paxKg','每名旅客')}{massField('bagKg','每名旅客行李')}{massField('freightKg','额外货物')}{massField('rampKg','停机坪燃油')}{massField('taxiKg','滑行耗油')}<button onClick={()=>perform(readFuelTarget)}>读取地面燃油目标</button></div><p className="lf-formula">ZFW = OEW + 旅客 + 行李 + 货物<br/>TOW = ZFW + 停机坪燃油 − 滑行耗油</p></section></div>
 {errors.length>0&&<div className="lf-error">输入待修正：{errors.join('；')}</div>}
 {f.departureReview&&(!f.departureReview.weather||!f.departureReview.runway)&&<div className="lf-warning"><b>起飞机场资料待复核</b><p>原机场 {f.departureReview.previousAirport} 的条件保留供核对；请在起飞页面核对天气及跑道，或重新采用对应机场天气，然后再保存确认。</p><button onClick={()=>h.push('/performance/engineering-takeoff')}>核对天气与跑道</button><button onClick={()=>h.push('/dispatch/local-weather')}>重新采用天气样例</button></div>}
 <div className="lf-toolbar"><button onClick={()=>h.push('/dispatch/engineering-plan')}>综合工程计划与报告</button><button onClick={()=>h.push('/ground/fuel')}>原生燃油页面</button><button onClick={()=>h.push('/ground/payload')}>原生载重页面</button><button onClick={()=>h.push('/dispatch/ofp')}>查看本地签派资料</button><span className="lf-muted">结构配置：MTOW 251000 kg；MZFW 181000 kg。速度表仅覆盖 130–250 t。</span></div>
 <div className="lf-warning"><b>两种计算方式均保留来源与适用范围</b><p>“离线起飞核算”使用上游 V2 参考表，仅供重量和速度参考检查；“工程起飞”使用独立工程假设模型，演示 V1 / VR / V2、推力、距离与限重计算。两者记录与报告分开。</p><p>本地计划和工程结果仅用于投标演示，尚未完成航空性能数据校准。</p></div></div>;
}
export function LocalTakeoffPage({engineering=false}:{engineering?:boolean}){
 const s=useLocal(),f=s.flight,h=useHistory(),r=s.result;const [lu,setLu]=useState<'m'|'ft'>('m');const [pu,setPu]=useState<'hPa'|'inHg'>('hPa');
 const update=(group:'runway'|'weather',key:string,v:any)=>editFlight(editDepartureInput(f,group,key,v));
 const field=(g:'runway'|'weather',key:string,label:string,type='number')=><Field key={key} name={key} label={label} type={type} value={(f[g] as any)[key]} onChange={v=>update(g,key,type==='number'?(v===''?NaN:Number(v)):v)}/>;
 const distance=(key:'tora'|'toda'|'asda'|'intersection',label:string)=><Field key={key} name={key} label={label+' ('+lu+')'} value={Number(lengthConvert(f.runway[key],'m',lu).toFixed(2))} onChange={v=>update('runway',key,lengthConvert(v===''?NaN:Number(v),lu,'m'))}/>;
 const stale=!!r&&(r.signature!==signature(f)||s.confirmed!==signature(f)||s.groundChanged);const valid=!!currentResult();
 return <div className="lf-root"><div className="lf-heading"><div><h2>{engineering?'工程起飞性能':'离线起飞核算'} <span className="lf-subtitle">{f.number} · {f.from} / {f.runway.ident}</span></h2><p>{engineering?'A330-941 工程演示模型 · V1 / VR / V2、推力与距离约束':'本地数据包与纯 TypeScript 内核 · 速度参考和准备检查'}</p></div><button onClick={()=>h.push('/dispatch/local-flight')}>编辑航班与重量</button></div>
 <WeightCards f={f}/><div className="lf-message" role="status">{s.storageError||s.notice}</div><StorageActions/>
 <div className="lf-cols"><section><h3>跑道与天气 <select aria-label="长度显示单位" value={lu} onChange={e=>setLu(e.target.value as any)}><option>m</option><option>ft</option></select></h3><div className="lf-grid">{field('runway','ident','跑道编号','text')}{field('runway','heading','跑道航向 (°)')}{distance('tora','TORA')}{distance('toda','TODA')}{distance('asda','ASDA')}{distance('intersection','距离扣减')}{field('runway','elevationFt','标高 (ft)')}{field('runway','slope','坡度 (%)')}{field('weather','windDir','风向 (°)')}{field('weather','windKt','风速 (kt)')}{field('weather','oat','气温 (°C)')}<Field name="qnh" label={'QNH ('+pu+')'} value={Number(pressureConvert(f.weather.qnh,'hPa',pu).toFixed(3))} onChange={v=>update('weather','qnh',pressureConvert(v===''?NaN:Number(v),pu,'hPa'))}/></div><div className="lf-toolbar"><label>压力单位 <select aria-label="压力显示单位" value={pu} onChange={e=>setPu(e.target.value as any)}><option>hPa</option><option>inHg</option></select></label><label>跑道条件 <select aria-label="跑道条件" value={f.runway.condition} onChange={e=>update('runway','condition',e.target.value)}><option value="dry">干燥</option><option value="wet">湿（未支持）</option><option value="contaminated">污染（未支持）</option></select></label></div><p className="lf-muted">资料来源：{f.runway.source}。{engineering?'模型对扣减后的 TORA / TODA / ASDA 分别检查地面距离、起飞距离和加速停止距离。':'TORA / TODA / ASDA 仅作声明距离一致性检查，未计算跑道性能余量。'}</p><p className="lf-muted">天气来源：{f.weather.source||'手工输入'}{f.weather.station?' · 站点 '+f.weather.station:''}。{f.weather.supersededSource?'原资料追溯：'+f.weather.supersededSource:''}</p>{((f.departureReview&&!f.departureReview.weather)||(f.weather.station&&f.weather.station!==f.from))&&<div className="lf-warning" role="alert">天气待复核。请逐项核对上方气象输入，再明确采用为 {f.from} 的手工条件；也可以重新选用匹配机场的天气样例。</div>}<div className="lf-toolbar"><button disabled={s.storageConflict} onClick={()=>perform(()=>editFlight(reviewManualWeather(f)))}>将当前天气确认为本机场手工条件</button><button onClick={()=>h.push('/dispatch/local-weather')}>重新采用天气样例</button>{f.departureReview&&!f.departureReview.runway&&<button disabled={s.storageConflict} onClick={()=>perform(()=>editFlight(reviewDepartureRunway(f)))}>已核对本机场跑道资料</button>}</div>{f.departureReview&&!f.departureReview.runway&&<p className="lf-error">跑道资料待复核：请检查编号、航向、三项声明距离、标高和坡度。</p>}</section>
 <section><h3>构型、确认与结果</h3><div className="lf-toolbar"><label>襟翼 <select aria-label="起飞襟翼" value={f.flaps} onChange={e=>editFlight({...f,flaps:Number(e.target.value)})}><option value="1">CONF 1+F</option><option value="2">CONF 2</option><option value="3">CONF 3</option></select></label><label><input type="checkbox" aria-label="防冰" checked={f.antiIce} onChange={e=>editFlight({...f,antiIce:e.target.checked})}/> 防冰</label><label><input type="checkbox" aria-label="空调引气" checked={f.packs} onChange={e=>editFlight({...f,packs:e.target.checked})}/> 空调引气</label></div><div className="lf-toolbar"><button onClick={()=>confirmFlight()}>保存并确认重量</button>{!engineering&&<button className="primary" onClick={()=>runCalculation()}>本地计算</button>}</div>
 {engineering?<EngineeringTakeoff />:<><div className={'lf-result '+(stale?'stale':'')} data-testid="takeoff-result"><b>{!r?'等待计算':stale?'结果已过期 — 请重新确认并计算':r.status==='reference-only'?'参考表核算完成 · 未校准':r.status==='unsupported'?'超出支持范围':'输入无效'}</b>
 {r&&<><div className="lf-speed">V2 参考 <strong>{r.v2===null?'—':n(r.v2,2)}<small> kt</small></strong></div><p>V1 —　VR —　FLEX —　起飞距离 —</p>{r.errors.length>0&&<p className="lf-error">{r.errors.join('；')}</p>}<p>压力高度 {r.pressureAltitudeFt===null?'—':n(r.pressureAltitudeFt)} ft<br/>迎风 {r.headwindKt===null?'—':n(r.headwindKt)} kt / 侧风 {r.crosswindKt===null?'—':n(r.crosswindKt)} kt<br/>扣减后 TORA {r.effectiveTora===null?'—':n(r.effectiveTora)} m</p><p className="lf-muted">此值仅是重量—构型表插值。风、气温、坡度、标高不修正 V2，不评估可起飞性。CONF 3 表的 220–230 t 跳变仍待数据核验。</p></>}
 </div><div className="lf-toolbar"><button disabled={!valid} onClick={()=>perform(archiveResult)}>保存记录</button><button disabled={!valid} onClick={()=>perform(()=>download('a339-reference-result.json',currentResult()))}>导出结果 JSON</button><button disabled={!valid} onClick={()=>perform(()=>download('a339-reference-report.html',reportHtml()))}>导出报告 HTML</button><button disabled={!valid} onClick={()=>perform(printReport)}>打印核算单</button></div></>}<button onClick={()=>h.push('/checklists')}>继续至原生检查单 →</button></section></div>
 {!engineering&&<><Scope/><section><h3>本机历史记录</h3>{s.history.length===0?<p className="lf-muted">暂无记录。保存参考核算后可恢复输入；恢复后需要再次确认与计算。</p>:s.history.map((x,i)=><div className="lf-history" key={i}><span>{x.input.number} · {x.input.from}/{x.input.runway.ident} · {x.at} · V2 参考 {n(x.v2||0,2)} kt</span><button onClick={()=>perform(()=>restoreHistory(i))}>恢复输入（需重算）</button></div>)}</section></>}</div>;
}
export function LocalGroundLink(){const s=useLocal(),ground=useRuntime();const h=useHistory(),last=ground.commands[0];return <div className="lf-groundbar"><div><b>本地计划</b>　{s.flight.number}　ZFW {n(weights(s.flight).zfw)} kg　停机坪燃油 {n(s.flight.rampKg)} kg　计划 {s.flight.pax} 人　<button onClick={()=>h.push('/dispatch/local-flight')}>编辑 / 确认本地载荷燃油</button></div><p>本地实际状态：{ground.pax} 人 / 货物 {n(ground.cargoKg)} kg / 燃油 {n(ground.fuelKg)} kg。登机采用已确认计划；下客仅将实际人数与货物卸载归零，不修改航班计划。</p><GroundPreparation/><div role="status" data-testid="ground-command-feedback">{last?<CommandReceipt command={last} flight={s.flight}/>:s.notice}</div></div>;}
