import type {planningBundle} from './planning-context';
type Bundle=ReturnType<typeof planningBundle>;
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const n=(v:number|null|undefined,places=0)=>v===null||v===undefined||!Number.isFinite(v)?'—':v.toLocaleString('en-US',{maximumFractionDigits:places});
export function planningReportHtml(b:Bundle){
 const fuel=b.fuel!,loading=b.loading!,land=b.landing,s=land.solution,t=fuel.totals!,m=fuel.planned!;
 const rows=[['滑行',t.taxiKg],['航路',t.tripKg],['航路裕量',t.contingencyKg],['复飞与备降',t.alternateKg],['最后储备',t.finalReserveKg],['额外',t.extraKg]] as const;
 let x=25;const total=rows.reduce((a,r)=>a+r[1],0),colors=['#778ca2','#237fa3','#66aaa0','#cb8b3c','#52744a','#9c8ac0'];
 const bars=rows.map(([name,v],i)=>{const width=v/total*650,chunk=`<rect x="${x}" y="20" width="${width}" height="28" fill="${colors[i]}"/><text x="25" y="${75+i*22}">${esc(name)} ${n(v)} kg</text>`;x+=width;return chunk;}).join('');
 const status=land.status==='engineering-feasible'?'着陆工程约束满足（仅在本模型内）':land.status==='engineering-infeasible'?'着陆工程约束不满足：以下仅为诊断结果':land.status==='unsupported'?'着陆条件超出支持范围':'着陆输入无效';
 const points=loading.points!;
 const cg=['zfw','ramp','takeoff','landing'].map(k=>{const p=points[k as keyof typeof points];return p?`<tr><td>${({zfw:'零燃油',ramp:'停机坪',takeoff:'起飞',landing:'目的地着陆'} as any)[k]}</td><td>${n(p.massKg)}</td><td>${n(p.momentKgM)}</td><td>${n(p.cgPercentMac,2)}</td><td>${p.withinCg&&p.withinMass?'工程约束满足':'超限'}</td></tr>`:'';}).join('');
 const chart=s?`<svg viewBox="0 0 720 135" role="img" aria-label="着陆需求与可用距离"><rect x="25" y="30" width="650" height="24" fill="#e8edf2"/><rect x="25" y="30" width="${Math.min(650,s.requiredDistanceM/Math.max(s.requiredDistanceM,land.input.runway.ldaM)*650)}" height="24" fill="${s.marginM<0?'#bf554d':'#237fa3'}"/><line x1="${25+land.input.runway.ldaM/Math.max(s.requiredDistanceM,land.input.runway.ldaM)*650}" x2="${25+land.input.runway.ldaM/Math.max(s.requiredDistanceM,land.input.runway.ldaM)*650}" y1="20" y2="65" stroke="#182f40" stroke-width="3"/><text x="25" y="90">需求 ${n(s.requiredDistanceM)} m / LDA ${n(land.input.runway.ldaM)} m / 余量 ${n(s.marginM)} m</text><text x="25" y="115">空中 ${n(s.airDistanceM)} + 延迟 ${n(s.delayDistanceM)} + 制动 ${n(s.brakingDistanceM)} m，距离系数 ${land.input.distanceFactor}</text></svg>`:'';
 return `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>${esc(b.flight.number)} 综合工程计划</title><style>body{font:16px/1.7 Arial,'Microsoft YaHei';max-width:940px;margin:36px auto;color:#1d3445}h1{font-size:30px}h2{border-bottom:2px solid #237fa3;margin-top:30px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:8px;border-bottom:1px solid #d2dce4}.note{padding:16px;background:#fff3d9;border-left:5px solid #c48b3a}svg{width:100%;font:15px Arial,'Microsoft YaHei'}pre{font-size:11px;white-space:pre-wrap;overflow-wrap:anywhere}small{color:#586b7a}@media print{button{display:none}h2{break-after:avoid}svg,tr{break-inside:avoid}}</style><button onclick="window.print()">打印 / 保存 PDF</button><h1>A330EFB 综合工程计划</h1><p>${esc(b.flight.number)} · ${esc(b.flight.date)} · ${esc(b.flight.from)} → ${esc(b.flight.to)} / 备降 ${esc(b.flight.alternate)}</p><p class="note">投标演示工程模型。计算采用项目公开列示的油耗、几何、制动等工程假设，未经航空性能校准。报告在导出时按当前已确认输入重新计算；${esc(land.label)}。</p><h2>航路与备降燃油</h2><p>当前停机坪燃油 ${n(b.flight.rampKg)} kg；建议 ${n(fuel.requiredRampKg)} kg。起飞 ${n(m.takeoffMassKg)} kg，目的地预计着陆 ${n(m.destinationLandingMassKg)} kg，备降预计着陆 ${n(m.alternateLandingMassKg)} kg。</p><svg viewBox="0 0 720 218" aria-label="燃油分项">${bars}</svg><p>目的地剩余燃油 ${n(m.destinationLandingFuelKg)} kg；继续备降后 ${n(m.alternateLandingFuelKg)} kg。分段距离和流量由用户录入，未解析或接入 AIRAC 航路。</p><h2>质量与纵向重心</h2><p>逐站质量乘以纵向力臂汇总力矩；重心位置除以总质量后换算为 %MAC。客舱分区、货舱站位和包线均为工程假设。</p><table><thead><tr><th>阶段</th><th>质量 kg</th><th>力矩 kg·m</th><th>重心 %MAC</th><th>状态</th></tr></thead><tbody>${cg}</tbody></table><p>备降着陆重心 ${n(b.alternateLoading?.points?.landing?.cgPercentMac,2)} %MAC。</p><h2>工程着陆</h2><p class="note"><b>${esc(status)}</b><br/>${esc([...land.errors,...land.warnings].join('；'))}</p><p>${esc(land.input.airport)} / ${esc(land.input.runway.ident)} · ${esc(land.input.configuration)} · ${esc(land.input.runway.condition)}。预计着陆重量 ${n(land.massKg)} kg。</p>${chart}<p>${land.status==='engineering-feasible'?'工程速度':'诊断速度（不可采用）'}：VREF ${n(s?.vrefKt,1)} kt，VAPP ${n(s?.vappKt,1)} kt；本模型场长限重 ${n(land.diagnostics.fieldLimitKg)} kg。${esc(land.errors.join('；'))}</p><p>跑道来源：${esc(land.input.runway.source)}。气象来源：${esc(land.input.weather.source)}。</p><h2>模型与追溯</h2><p>燃油 ${esc(fuel.model.version)}；配载 ${esc(loading.model.version)}；着陆 ${esc(land.model.version)}。生成于 ${esc(b.at)}。</p><details><summary>输入、结果及参数来源完整快照</summary><pre>${esc(JSON.stringify(b,null,2))}</pre></details></html>`;
}
