import {landingParameters} from './engine';
import type {LandingResult} from './types';
const n=(v:number,d=0)=>Number.isFinite(v)?v.toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d}):'—';
const esc=(v:unknown)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));

/** Profile and distance bands are drawn from this result's actual numerical trajectory. */
export function landingChartSvg(result:LandingResult):string {
 const s=result.solution;if(!s)return '';
 const left=58,right=740,width=800,maxDistance=Math.max(result.input.runway.ldaM,s.requiredDistanceM)*1.08,x=(d:number)=>left+d/maxDistance*(right-left);
 const slope=result.input.runway.slopePercent/100,heights=s.trajectory.map(p=>p.heightM+(p.phase==='braking'?p.distanceM*slope:0));
 const minH=Math.min(0,slope*result.input.runway.ldaM),maxH=Math.max(20,slope*result.input.runway.ldaM,...heights),y=(h:number)=>175-(h-minH)/(maxH-minH)*125;
 const runwayY=(d:number)=>y(d*slope);
 const profile=s.trajectory.map((p,i)=>`${i?'L':'M'} ${x(p.distanceM).toFixed(1)} ${y(p.heightM+p.distanceM*slope).toFixed(1)}`).join(' ');
 const lines=Array.from({length:5},(_,i)=>{const d=i*maxDistance/4;return `<line x1="${x(d)}" x2="${x(d)}" y1="42" y2="186" stroke="#485764" stroke-opacity=".3"/><text x="${x(d)}" y="207" text-anchor="middle">${n(d)} m</text>`;}).join('');
 const segments=[{label:'空中段',length:s.airDistanceM,color:'#86bfe9'},{label:'制动延迟',length:s.delayDistanceM,color:'#dcae55'},{label:'减速滑跑',length:s.brakingDistanceM,color:'#51bda6'}];
 let offset=0;const bars=segments.map((segment,i)=>{const start=offset;offset+=segment.length;return `<rect x="${x(start)}" y="237" width="${x(offset)-x(start)}" height="20" fill="${segment.color}"/><rect x="${left+i*230}" y="286" width="11" height="11" fill="${segment.color}"/><text x="${left+18+i*230}" y="296">${segment.label} ${n(segment.length)} m</text>`;}).join('');
 const reserve=s.requiredDistanceM-s.unfactoredDistanceM;
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} 386" role="img" aria-label="工程着陆纵剖面与距离分解" style="width:100%;height:auto;font:13px Arial,sans-serif;color:inherit"><title>当前工程模型的着陆轨迹与 LDA 距离比较</title><g fill="currentColor"><text x="${left}" y="21">阈值 50 ft → 接地 → 停止；纵向高度比例独立于距离</text>${lines}<path d="M ${x(0)} ${runwayY(0)} L ${x(result.input.runway.ldaM)} ${runwayY(result.input.runway.ldaM)}" stroke="#70869a" stroke-width="8" fill="none"/><path d="${profile}" stroke="#6fceb2" stroke-width="3" fill="none"/><circle cx="${x(s.airDistanceM)}" cy="${runwayY(s.airDistanceM)}" r="4" fill="#e6b755"/><text x="${left}" y="226">未乘系数距离 ${n(s.unfactoredDistanceM)} m</text>${bars}<rect x="${x(s.unfactoredDistanceM)}" y="237" width="${x(s.requiredDistanceM)-x(s.unfactoredDistanceM)}" height="20" fill="#d89c52" fill-opacity=".4" stroke="#d89c52" stroke-dasharray="3 3"/><line x1="${x(result.input.runway.ldaM)}" x2="${x(result.input.runway.ldaM)}" y1="215" y2="270" stroke="${s.marginM<0?'#fa887c':'#dbe4e9'}" stroke-width="2"/><text x="${x(result.input.runway.ldaM)}" y="278" text-anchor="end">LDA ${n(result.input.runway.ldaM)} m</text><text x="${left}" y="323">附加余量 ${n(reserve)} m（系数 ${n(result.input.distanceFactor,2)}） · 工程需求 ${n(s.requiredDistanceM)} m</text><text x="${left}" y="350" fill="${s.marginM<0?'#fa887c':'#6fceb2'}">${s.marginM<0?'距离不足':'剩余距离'} ${n(Math.abs(s.marginM))} m · 坡度 ${n(result.input.runway.slopePercent,1)}%</text><text x="${left}" y="376">轨迹仅表示本模型的分段假设；不提供实际进近操纵指引。</text></g></svg>`;
}
export function landingReportHtml(result:LandingResult):string {
 const s=result.solution;
 return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><title>A330EFB 工程着陆报告</title><style>body{font:15px/1.6 Arial,'Microsoft YaHei',sans-serif;max-width:940px;margin:30px auto;padding:0 24px;color:#183044}h1{font-size:26px}h2{font-size:20px}aside{padding:15px;border:2px solid #a57730;background:#fff8e9}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:11px/1.5 Consolas,monospace}figure{margin:20px 0;break-inside:avoid}button{padding:8px 16px}@media print{button{display:none}}</style></head><body><button onclick="window.print()">打印 / 保存 PDF</button><h1>A330EFB 工程着陆报告</h1><aside><b>${esc(result.label)}</b><br>本模型不是 Airbus AFM / FCOM 计算工具，也不用于实际着陆或签派。</aside><p>航班 ${esc(result.context?.flight?.number)} · ${esc(result.input?.airport)} / ${esc(result.input?.runway?.ident)} · ${esc(result.input?.target==='alternate'?'备降场':'目的地')}</p><p>状态：${esc(result.status)} · 重量 ${n(result.massKg)} kg · 来源 ${esc(result.context?.massSource)}</p>${s?`<h2>${s.marginM<0?'不可行工程诊断':'工程计算结果'}</h2><p>Vref ${n(s.vrefKt,1)} kt CAS；Vapp ${n(s.vappKt,1)} kt CAS。速度均为工程假设${s.marginM<0?'，不构成可用建议':''}。</p><p>空中 ${n(s.airDistanceM)} m；延迟 ${n(s.delayDistanceM)} m；减速 ${n(s.brakingDistanceM)} m；乘系数后 ${n(s.requiredDistanceM)} m；LDA 余量 ${n(s.marginM)} m。</p><p>场长工程限重 ${s.fieldLimitKg===null?'无可行档位':n(s.fieldLimitKg)+' kg'}；${esc(s.limitReason)}。</p><figure>${landingChartSvg(result)}</figure>`:'<p>输入无效或超出支持范围，未生成速度与距离结果。</p>'}<h2>诊断</h2><ul>${[...result.errors,...result.warnings].map(item=>`<li>${esc(item)}</li>`).join('')}</ul><h2>参数与公开参考资料</h2><pre>${esc(JSON.stringify(landingParameters,null,2))}</pre><h2>输入、来源、版本及结果快照</h2><pre>${esc(JSON.stringify(result,null,2))}</pre></body></html>`;
}
