import type {Action,Scenario,Step} from './types';
const nav=(route:string,ready:string):Action=>({type:'nav',route,ready});
const button=(name:string):Action=>({type:'button',name});
const field=(name:string,value:string):Action=>({type:'field',name,value});
const expect=(values:Record<string,string|number|boolean|null>):Action=>({type:'expect',values});
const focus=(selector:string):Action=>({type:'focus',selector});
const flight=nav('/dispatch/local-flight','.lf-root [data-field="number"]');
const perf=nav('/performance/local-takeoff','[data-testid="takeoff-result"]');
const engineeringPerf=nav('/performance/engineering-takeoff','[data-testid="engineering-takeoff"]');
const confirm=button('保存并确认重量');
const calc=button('本地计算');
const engineeringCalc=button('计算工程起飞性能');
const steps:Step[]=[
 {id:'overview',chapter:'01 / 航班准备',title:'从统一工作台开始',description:'围绕一份航班计划完成签派资料、载荷燃油和参考计算。左侧为正在运行的 Headwind EFB，演示脚本会实际操作这些页面。',watch:'本地场景资料 · 全程可暂停并接管操作',manual:'技术说明书 2.0 · 第 18 章',seconds:10,actions:[nav('/dashboard','a[href="/dispatch"]')]},
 {id:'flight-import',chapter:'01 / 航班准备',title:'导入航班，建立统一输入',description:'载入 DEMO330 本地航班文件。起飞 ZUTF、目的 ZSPD，250 名旅客，停机坪燃油 30,000 kg。文件经过程序原有的 JSON 解析和字段校验。',watch:'航班号、机场、质量数据同时进入工作台',manual:'技术说明书 2.0 · 19.1–19.4',seconds:18,actions:[flight,button('新建航班'),{type:'import'},expect({flightNumber:'DEMO330',tow:184500,confirmed:false}),focus('.lf-cols')]},
 {id:'load-edit',chapter:'01 / 航班准备',title:'人数改变，重量同步变化',description:'将旅客人数从 250 改为 260。每人及行李合计 104 kg，因此载荷和起飞重量同步增加 1,040 kg。重量卡片由实际输入实时计算。',watch:'TOW：184,500 → 185,540 kg',manual:'技术说明书 2.0 · 20.1',seconds:16,actions:[field('pax','260'),expect({tow:185540,zfw:156040}),focus('.lf-metrics')]},
 {id:'load-restore',chapter:'01 / 航班准备',title:'恢复本次演示计划',description:'将旅客人数恢复为 250，检查空重、载荷、零燃油重量和起飞重量之间的关系。本次后续演示采用这份基础计划。',watch:'ZFW 155,000 kg · TOW 184,500 kg',manual:'技术说明书 2.0 · 20.1–20.2',seconds:12,actions:[field('pax','250'),expect({zfw:155000,tow:184500}),focus('.lf-metrics')]},
 {id:'confirm',chapter:'01 / 航班准备',title:'确认重量并同步专业页面',description:'保存并确认重量后，当前计划同步到仪表盘、签派资料以及载荷和燃油目标。确认动作建立本次计算采用的输入版本。',watch:'观察蓝色状态提示：本地航班与重量已确认',manual:'技术说明书 2.0 · 19.5',seconds:14,actions:[confirm,expect({confirmed:true}),focus('.lf-message')]},
 {id:'dashboard',chapter:'02 / 页面协同',title:'仪表盘读取同一航班',description:'返回仪表盘，航班号、出发与目的机场、人数和重量摘要均来自刚才确认的计划。演示中的时刻和航路为本地样例。',watch:'DEMO330 · ZUTF → ZSPD · 250 名旅客',manual:'技术说明书 2.0 · 18.2、19.5',seconds:14,actions:[nav('/dashboard','a[href="/dispatch"]'),expect({flightNumber:'DEMO330',confirmed:true})]},
 {id:'ofp',chapter:'02 / 页面协同',title:'查看本地签派资料',description:'打开 OFP 阅读页。程序根据已确认输入生成航班、载荷、燃油与重量摘要，供现场评审核对跨页面的一致性。',watch:'同一计划形成可阅读的签派摘要',manual:'技术说明书 2.0 · 19.6',seconds:15,actions:[nav('/dispatch/ofp','a[href="/dispatch"]')]},
 {id:'payload',chapter:'02 / 页面协同',title:'载重页面与客舱分布',description:'原生载重页面呈现座位和货舱布局，并显示计划人数、货物与重量数据。这里展示原生 EFB 与本地航班的联动。',watch:'计划人数 250 · ZFW 155,000 kg',manual:'技术说明书 2.0 · 20.4',seconds:15,actions:[nav('/ground/payload','.lf-groundbar'),expect({zfw:155000})]},
 {id:'fuel',chapter:'02 / 页面协同',title:'燃油目标与油箱页面',description:'原生燃油页面按油箱展示本地演示状态。当前计划停机坪燃油为 30,000 kg，后续将用它演示目标变化与重新确认。',watch:'核对页面上方的本地计划与目标油量',manual:'技术说明书 2.0 · 20.3',seconds:15,actions:[nav('/ground/fuel','.lf-groundbar'),expect({fuelTarget:30000})]},
 {id:'performance-input',chapter:'03 / 参考核算',title:'核对跑道、天气与构型',description:'进入离线参考核算。场景使用 3,500 m 声明距离、标准气压和 CONF 1+F。输入界面与航班工作台共用同一份 Flight 数据。',watch:'本演示展示重量和源码表 V2 参考核算',manual:'技术说明书 2.0 · 21.1–21.2',seconds:18,actions:[perf,focus('.lf-cols')]},
 {id:'calculate',chapter:'03 / 参考核算',title:'运行实际计算并解释结果',description:'执行本地计算，184.5 t、CONF 1+F 对应 V2 参考 150.8 kt。界面同时显示风分量、压力高度和距离扣减；参考值不等同于完整起飞性能判定。',watch:'实际函数结果：V2 150.8 kt',manual:'技术说明书 2.0 · 10.3、21.2',seconds:20,actions:[calc,expect({v2:150.8,valid:true}),focus('[data-testid="takeoff-result"]')]},
 {id:'history',chapter:'03 / 参考核算',title:'保存带输入快照的历史',description:'保存当前核算记录。记录保留航班输入、资料与内核版本，便于复核这一次结果的来历；恢复历史后仍需重新确认。',watch:'历史记录新增 1 条',manual:'技术说明书 2.0 · 21.4',seconds:15,actions:[button('保存记录'),expect({history:1}),focus('.lf-history')]},
 {id:'report',chapter:'03 / 参考核算',title:'生成可交付的核算报告',description:'预览由程序实际生成的 HTML 报告。报告包含输入快照、参考结果和版本信息，可在暂停演示后保存 JSON 或 HTML。',watch:'报告数据直接读取当前有效结果',manual:'技术说明书 2.0 · 21.5',seconds:20,actions:[{type:'report'}]},
 {id:'ground-change',chapter:'04 / 变更复核',title:'地面燃油目标发生变化',description:'把原生燃油页面的目标从 30,000 kg 改为 31,000 kg。程序保留已确认的航班输入，同时标记地面目标发生变化。',watch:'运行目标改变；原计划等待用户核对',manual:'技术说明书 2.0 · 20.3、20.5',seconds:16,actions:[{type:'closeReport'},nav('/ground/fuel','.lf-groundbar'),{type:'fuel',value:31000},expect({fuelTarget:31000,groundChanged:true}),focus('.lf-groundbar')]},
 {id:'stale',chapter:'04 / 变更复核',title:'旧结果失效，出口受到控制',description:'返回参考核算页，旧数值仍可回看，但程序显示结果已过期并禁用当前报告出口。这一状态来自真实业务规则。',watch:'“结果已过期”与灰色导出按钮',manual:'技术说明书 2.0 · 20.5、21.3',seconds:18,actions:[perf,expect({valid:false,groundChanged:true}),focus('[data-testid="takeoff-result"]')]},
 {id:'reconcile',chapter:'04 / 变更复核',title:'读取新目标，重新确认计划',description:'回到航班工作台，读取地面燃油目标，再保存确认。新的起飞重量为 185,500 kg，用户明确采用了这份更新后的计划。',watch:'停机坪燃油 31,000 kg · TOW 185,500 kg',manual:'技术说明书 2.0 · 20.5',seconds:20,actions:[flight,button('读取地面燃油目标'),expect({fuel:31000,tow:185500,confirmed:false}),confirm,expect({confirmed:true,groundChanged:false}),focus('.lf-metrics')]},
 {id:'recalculate',chapter:'04 / 变更复核',title:'重算形成新的有效结果',description:'按新重量重新计算并保存记录，V2 参考变为 151.2 kt。两次历史记录分别对应各自的输入快照，完成变更复核过程。',watch:'V2：150.8 → 151.2 kt · 历史 2 条',manual:'技术说明书 2.0 · 21.3–21.4',seconds:18,actions:[perf,calc,button('保存记录'),expect({v2:151.2,valid:true,history:2}),focus('[data-testid="takeoff-result"]')]},
 {id:'checklist',chapter:'05 / 专业工具',title:'在原生检查单中逐项确认',description:'切换到驾驶舱准备检查单，勾选 GEAR PINS & COVERS。检查单由原生页面管理，勾选后条目颜色和完成状态同步改变。',watch:'一个实际检查项完成，页面保留勾选状态',manual:'技术说明书 2.0 · 22.1',seconds:20,actions:[nav('/checklists','a[href="/checklists"]'),{type:'checklist',item:'GEAR PINS & COVERS'},expect({checkedItems:1})]},
 {id:'tod',chapter:'05 / 专业工具',title:'下降顶点工具',description:'输入当前高度 35,000 ft、目标高度 3,000 ft 和 3° 下降角。原生工具按几何关系给出约 100 NM 的下降距离。',watch:'35,000 → 3,000 ft · 3° · 约 100 NM',manual:'技术说明书 2.0 · 21.6',seconds:20,actions:[nav('/performance/top-of-descent','input'),{type:'nativeInputs',values:['35000','3000','3']},expect({todAltitude:35000,todTarget:3000})]},
 {id:'finish',chapter:'06 / 场景回顾',title:'完成典型航班准备演示',description:'已展示文件建档、重量核对、跨页面同步、参考计算、历史与报告，以及地面变更后的失效和重算。可重播场景，或暂停后在真实页面自由操作。',watch:'演示记录和业务文件可从右上角“演示资料”保存',manual:'技术说明书 2.0 · 第 18–22 章',seconds:12,actions:[perf,expect({valid:true,v2:151.2,history:2}),focus('[data-testid="takeoff-result"]')]},
];
const by=(id:string)=>steps.find(s=>s.id===id)!;
const base:Step={id:'base',chapter:'01 / 基础计划',title:'建立本次场景的基础计划',description:'导入与项目手册一致的 DEMO330 样例，确认 184,500 kg 起飞重量，计算并保存 150.8 kt 的 V2 参考记录。',watch:'本场景使用独立的演示会话',manual:'技术说明书 2.0 · 第 19–21 章',seconds:14,actions:[flight,{type:'import'},confirm,perf,calc,button('保存记录'),expect({valid:true,v2:150.8,history:1})]};
const landing:Step={id:'landing',chapter:'02 / 专业工具',title:'着陆工具录入与计算',description:'使用手册中的 190 t、FULL 构型样例，展示原生着陆页的录入、计算和三档制动结果。此处用于说明软件流程，算法资料的校准边界见手册第 11 章。',watch:'参数录入后执行原生页面“计算”',manual:'技术说明书 2.0 · 11.3–11.4、21.6',seconds:20,actions:[nav('/performance/landing','input'),{type:'nativeInputs',values:[null,'170','3500','20','0','0','15','1013','190000','145']},button('计算')]};
const toolsEnd:Step={id:'tools-finish',chapter:'03 / 场景回顾',title:'专业工具巡览完成',description:'已展示载荷、燃油、检查单、下降顶点和着陆工具。可通过底部步骤条定位任一功能，或接管真实 EFB 继续操作。',watch:'“重播”会重新建立该场景的演示数据',manual:'技术说明书 2.0 · 第 20–22 章',seconds:10,actions:[nav('/dashboard','a[href="/dispatch"]')]};
export const scenarios:Scenario[]=[
 {id:'preflight',name:'典型航班准备',summary:'建档 → 重量 → 页面协同 → 核算报告 → 变更复核 → 检查单',steps},
 {id:'change',name:'地面变更与重算',summary:'基础结果 → 燃油变更 → 结果失效 → 重新确认 → 新报告',steps:[base,by('ground-change'),by('stale'),by('reconcile'),by('recalculate'),by('report'),by('finish')]},
 {id:'tools',name:'专业工具巡览',summary:'载荷与燃油 → 检查单 → 下降顶点 → 着陆计算',steps:[base,by('payload'),by('fuel'),by('checklist'),by('tod'),landing,toolsEnd]},
 {id:'resources',name:'资料与地面协同',summary:'资料阅读 → 天气采用 → 地面准备 → 故障恢复 → 推出',steps:[base,
  {id:'charts',chapter:'01 / 资料准备',title:'阅读离线图件',description:'打开项目自制的机场布局示意，放大后旋转并复位。所有内置资料随项目构建提供，现场不需要外网。',watch:'图件带有演示用途标识',manual:'1.1 操作补充说明 §2',seconds:14,actions:[nav('/navigation/local-files','[data-testid="offline-charts"]'),button('放大'),button('旋转'),button('复位视图'),focus('[data-testid="chart-viewport"]')]},
  {id:'weather-adopt',chapter:'01 / 资料准备',title:'采用一份带来源的天气',description:'在天气页面核对机场、时间与报文，明确采用到航班。旧确认和旧计算立即失效，需要重新确认计划。',watch:'固定天气样例，不表示机场实况',manual:'1.1 操作补充说明 §3',seconds:14,actions:[nav('/dispatch/local-weather','[data-testid="offline-weather"]'),button('采用到当前航班'),expect({confirmed:false,valid:false})]},
  {id:'weather-confirm',chapter:'01 / 资料准备',title:'确认新天气并重新计算',description:'返回航班工作台确认，再执行参考核算。新结果记录这次采用的资料来源和时间。',watch:'计划、天气与结果具有同一输入快照',manual:'1.1 操作补充说明 §3',seconds:12,actions:[flight,confirm,perf,calc,expect({confirmed:true,valid:true})]},
  {id:'parked',chapter:'02 / 地面准备',title:'恢复停机待服务状态',description:'使用停机预设清空地面回执，设定 5000 kg 油量和 0 名旅客。新会话不会继续执行上一会话的动作。',watch:'当前状态与计划目标分开显示',manual:'1.1 操作补充说明 §4',seconds:12,actions:[nav('/presets','[data-testid="local-presets"]'),button('恢复停机预设'),expect({currentFuel:5000,currentPax:0,gpuConnected:false})]},
  {id:'gpu',chapter:'02 / 地面准备',title:'连接地面电源',description:'提交连接请求，查看受理、执行与完成回执。完成后设备状态变为已连接。',watch:'状态由本地演示模型推进',manual:'1.1 操作补充说明 §4',seconds:12,actions:[nav('/ground/services','[data-testid="local-simulation"]'),button('连接外接电源'),expect({gpuConnected:true,lastCommandStatus:'completed'})]},
  {id:'refuel',chapter:'02 / 地面准备',title:'按确认计划加油',description:'把当前油量从 5000 kg 加至计划的 30000 kg。各油箱使用同一分配规则，原生燃油页也能读取变化后的油量。',watch:'进度结束后核对 30000 kg',manual:'1.1 操作补充说明 §4',seconds:14,actions:[button('按计划加油'),expect({currentFuel:30000,lastCommandStatus:'completed'})]},
  {id:'board',chapter:'02 / 地面准备',title:'按计划完成登机',description:'执行 250 名旅客的登机演示，并将最终状态写入本地客舱变量。',watch:'计划 250 名，完成后当前人数 250',manual:'1.1 操作补充说明 §4',seconds:14,actions:[button('按计划登机'),expect({currentPax:250,lastCommandStatus:'completed'})]},
  {id:'fault',chapter:'03 / 故障恢复',title:'激活电源故障',description:'激活外接电源故障，观察电源连接被中断。此故障只影响当前浏览器中的演示模型。',watch:'故障状态与地面设备状态保持一致',manual:'1.1 操作补充说明 §5',seconds:12,actions:[nav('/failures','[data-testid="local-faults"]'),button('激活电源故障'),expect({gpuConnected:false,activeFaults:1})]},
  {id:'fault-reject',chapter:'03 / 故障恢复',title:'故障条件下拒绝连接',description:'故障未解除时再次连接电源，程序返回明确拒绝回执，设备不会显示为已连接。',watch:'拒绝原因可以直接复核',manual:'1.1 操作补充说明 §5',seconds:12,actions:[nav('/ground/services','[data-testid="local-simulation"]'),button('连接外接电源'),expect({lastCommandStatus:'rejected',gpuConnected:false})]},
  {id:'fault-recover',chapter:'03 / 故障恢复',title:'解除故障并恢复设备',description:'解除电源故障后重新提交连接请求，确认本次请求能够完成。',watch:'解除故障不会自动补发旧命令',manual:'1.1 操作补充说明 §5',seconds:14,actions:[nav('/failures','[data-testid="local-faults"]'),button('解除电源故障'),nav('/ground/services','[data-testid="local-simulation"]'),button('连接外接电源'),expect({gpuConnected:true,activeFaults:0,lastCommandStatus:'completed'})]},
  {id:'pushback',chapter:'04 / 离位准备',title:'断开电源并演示推出',description:'断开外接电源，再提交推出请求。模型推进至 30 米示意距离，完成本次资料与地面协同。',watch:'本地推出示意，不驱动真实飞机位置',manual:'1.1 操作补充说明 §4',seconds:16,actions:[button('断开外接电源'),expect({gpuConnected:false,lastCommandStatus:'completed'}),button('请求推出'),expect({pushbackMetres:30,lastCommandStatus:'completed'})]},
 ]},
 {id:'takeoff',name:'工程起飞性能',summary:'确认计划 → TOGA → FLEX → 轨迹与余量 → 短跑道无解 → 恢复重算 → 工程报告',steps:[
  {id:'engineering-base',chapter:'01 / 工程计算准备',title:'确认本次计算的航班输入',description:'导入 DEMO330 样例并保存确认，采用 184,500 kg 起飞重量和 3,500 m 声明距离。本场景使用公开列示的工程假设，展示数值求解与软件流程。',watch:'未经航空性能校准；结果只表示本模型内的约束状态',manual:'起飞性能操作说明 · §1',seconds:16,actions:[flight,{type:'import'},confirm,expect({flightNumber:'DEMO330',tow:184500,confirmed:true}),engineeringPerf,expect({engineeringActive:true,engineeringValid:false}),focus('[data-testid="engineering-takeoff"]')]},
  {id:'engineering-toga',chapter:'02 / 速度与推力',title:'按 TOGA 工程模型求解',description:'选择 TOGA 并执行计算。程序搜索满足继续起飞、加速停止、地面滑跑及工程爬升条件的 V1，计算 VR、V2、需求距离与 TOGA 工程限制重量。',watch:'速度、距离和限制因素来自本次计算',manual:'起飞性能操作说明 · §2',seconds:20,actions:[button('使用 TOGA'),engineeringCalc,expect({engineeringValid:true,engineeringStatus:'engineering-feasible',engineeringMode:'TOGA',engineeringThrustMode:'TOGA'}),focus('[data-testid="engineering-result"]')]},
  {id:'engineering-flex',chapter:'02 / 速度与推力',title:'切换 FLEX 并重新求解',description:'通过实际按钮切换 FLEX，撤下前一次结果，然后按假设温度搜索减推力工程解。每个候选温度都重新核对速度和距离约束；减推力不可行时模型尝试 TOGA。',watch:'FLEX 采用工程推力假设，不代表 Trent 7000 已校准性能',manual:'起飞性能操作说明 · §2',seconds:20,actions:[button('使用 FLEX'),expect({engineeringValid:false,engineeringStatus:'stale',engineeringMode:'FLEX'}),engineeringCalc,expect({engineeringValid:true,engineeringStatus:'engineering-feasible',engineeringMode:'FLEX'}),focus('[data-testid="engineering-result"]')]},
  {id:'engineering-chart',chapter:'03 / 图形复核',title:'查看两条轨迹与声明距离',description:'图中展示当前解的继续起飞和加速停止轨迹，并分别比较 TORA、TODA、ASDA 的模型需求与可用距离。曲线直接读取求解轨迹。',watch:'观察速度—距离曲线与三条距离余量',manual:'起飞性能操作说明 · §3',seconds:18,actions:[focus('[data-testid="engineering-chart"]'),expect({engineeringValid:true})]},
  {id:'engineering-stale',chapter:'04 / 条件变更',title:'缩短跑道使旧结果失效',description:'把 TORA、TODA 和 ASDA 同时改为 1,000 m。修改后原确认失效，旧速度和曲线撤下；当前结果与报告不能继续使用。',watch:'输入变更后必须重新确认和计算',manual:'起飞性能操作说明 · §4',seconds:16,actions:[field('tora','1000'),field('toda','1000'),field('asda','1000'),expect({confirmed:false,engineeringValid:false,engineeringStatus:'stale'}),focus('[data-testid="engineering-result"]')]},
  {id:'engineering-infeasible',chapter:'04 / 条件变更',title:'确认短跑道并查看无解诊断',description:'确认新的跑道条件后重新计算。当前重量在本模型的短跑道条件下不可行，结果区显示诊断而不提供可采用的速度。',watch:'“工程模型不可行”仅表示已实现约束没有可行解',manual:'起飞性能操作说明 · §4',seconds:18,actions:[confirm,engineeringCalc,expect({confirmed:true,engineeringValid:false,engineeringStatus:'engineering-infeasible'}),focus('[data-testid="engineering-result"]')]},
  {id:'engineering-restore',chapter:'04 / 条件变更',title:'恢复条件，形成新的有效工程解',description:'将三项声明距离恢复为 3,500 m，重新确认并计算。新结果使用更新后的输入快照，完成条件变更、失效、诊断和重算过程。',watch:'重新获得当前输入下的可行工程解',manual:'起飞性能操作说明 · §4',seconds:18,actions:[field('tora','3500'),field('toda','3500'),field('asda','3500'),confirm,engineeringCalc,expect({confirmed:true,engineeringValid:true,engineeringStatus:'engineering-feasible'}),focus('[data-testid="engineering-chart"]')]},
  {id:'engineering-report',chapter:'05 / 结果归档',title:'预览本次工程起飞报告',description:'打开程序生成的工程报告，核对输入、计算选项、数值结果、轨迹、模型版本、参数假设和未覆盖范围。可通过演示资料保存 JSON 和 HTML。',watch:'报告与页面采用同一个有效计算结果',manual:'起飞性能操作说明 · §5',seconds:20,actions:[expect({engineeringValid:true}),{type:'report'}]},
 ]},
];
