/** Capture actual program views in an isolated browser; never alter the user's saved flight. */
const path=require('node:path'),fs=require('node:fs');
const {chromium}=require(process.env.A330EFB_DOC_NODE_MODULES?path.join(process.env.A330EFB_DOC_NODE_MODULES,'playwright'):'playwright');
const root=path.resolve(__dirname,'../..'),out=path.join(__dirname,'assets'),base=process.env.EFB_BASE_URL||'http://127.0.0.1:9698';fs.mkdirSync(out,{recursive:true});
const onlyDemos=process.argv.includes('--only-demos');
(async()=>{const browser=await chromium.launch({headless:true}),c=await browser.newContext({viewport:{width:1920,height:1080},acceptDownloads:true}),p=await c.newPage(),records=onlyDemos?JSON.parse(fs.readFileSync(path.join(__dirname,'capture.json'),'utf8')).records.filter(r=>!r.scenario):[],errors=[];p.setDefaultTimeout(25000);p.on('pageerror',e=>errors.push(e.message));
await c.route('**/*',r=>{const u=new URL(r.request().url());return u.origin===new URL(base).origin||['blob:','data:'].includes(u.protocol)?r.continue():r.abort();});
const nav=async r=>{await p.evaluate(r=>window.__EFB_NAVIGATE(r),r);await p.waitForTimeout(350);};
const shot=async(name,selector='.lf-root',last=false)=>{const l=last?p.locator(selector).last():p.locator(selector).first();await l.scrollIntoViewIfNeeded();await l.screenshot({path:path.join(out,name+'.png')});records.push({name,route:await p.evaluate(()=>location.pathname),selector,at:new Date().toISOString(),flight:await p.evaluate(()=>window.__LOCAL_FLIGHT__?.getState().flight.number)});};
const confirm=()=>p.evaluate(()=>window.__LOCAL_FLIGHT__.confirmFlight());
try{
 if(!onlyDemos){
 await p.goto(base);await p.waitForFunction(()=>window.__LOCAL_FLIGHT__&&window.__EFB_NAVIGATE);await p.waitForTimeout(2800);
 await shot('home','#instrument');await nav('/dispatch/local-flight');await shot('flight');await shot('weights','.lf-cols section',true);
 await p.locator('[data-field="freightKg"]').fill('');await shot('draft');await p.locator('[data-field="freightKg"]').fill('2000');
 await nav('/dispatch/local-weather');await shot('weather','[data-testid="offline-weather"]');
 await nav('/dispatch/engineering-plan');await p.getByRole('button',{name:'建立三项工程计划',exact:true}).click();await shot('plan');
 await nav('/dispatch/fuel-plan');await p.getByRole('button',{name:'计算航路燃油',exact:true}).click();await shot('fuel-input','[data-testid="fuel-planning"]');await shot('fuel-profile','[data-testid="fuel-profile"]');await shot('fuel-result','[data-testid="fuel-plan-result"]');
 await p.getByRole('button',{name:'采用建议停机坪燃油',exact:true}).click();
 await nav('/ground/loading-balance');await p.getByRole('button',{name:'按计划自动分配',exact:true}).click();await p.getByRole('button',{name:'确认配载方案',exact:true}).click();await confirm();await shot('loading-input','.engineering-loading .lf-cols');await shot('loading-stations','[data-testid="loading-stations"]');await shot('loading-envelope','[data-testid="loading-envelope"]');await shot('loading-result','[data-testid="loading-result"]');
 await nav('/performance/engineering-landing');await shot('landing-input','[data-testid="engineering-landing"]');await p.getByRole('button',{name:'计算工程着陆性能',exact:true}).click();await shot('landing-result','[data-testid="landing-result"]');await shot('landing-chart','[data-testid="landing-chart"]');
 await p.getByLabel('可用着陆距离 LDA (m)',{exact:true}).fill('300');await p.getByLabel('着陆跑道坡度 (%)',{exact:true}).fill('-2');await confirm();await p.getByRole('button',{name:'计算工程着陆性能',exact:true}).click();await shot('landing-diagnostic','[data-testid="landing-chart"]');
 await p.getByLabel('可用着陆距离 LDA (m)',{exact:true}).fill('3000');await p.getByLabel('着陆跑道坡度 (%)',{exact:true}).fill('0');await p.getByLabel('着陆目标',{exact:true}).selectOption('alternate');await p.getByRole('button',{name:'重设为备降场工程示例',exact:true}).click();await confirm();await p.getByRole('button',{name:'计算工程着陆性能',exact:true}).click();await shot('alternate','[data-testid="landing-result"]');
 await nav('/dispatch/engineering-plan');await shot('plan-confirmed');const html=await p.evaluate(()=>window.__LOCAL_PLANNING__.artifacts().report);const report=await c.newPage();await report.setContent(html);await report.screenshot({path:path.join(out,'report.png'),fullPage:false});await report.close();
 await nav('/performance/engineering-takeoff');await confirm();await p.getByRole('button',{name:'使用 TOGA',exact:true}).click();await p.getByRole('button',{name:'计算工程起飞性能',exact:true}).click();await p.waitForFunction(()=>window.__TAKEOFF_ENGINEERING__?.snapshot().result?.solution);await shot('takeoff-result','[data-testid="engineering-result"]');await shot('takeoff-chart','[data-testid="engineering-chart"]');await p.getByRole('button',{name:'使用 FLEX',exact:true}).click();await p.getByRole('button',{name:'计算工程起飞性能',exact:true}).click();await p.waitForFunction(()=>window.__TAKEOFF_ENGINEERING__?.snapshot().result?.options.mode==='FLEX');await shot('takeoff-flex','[data-testid="engineering-result"]');
 await p.evaluate(()=>window.__LOCAL_RUNTIME__.preset('prepared'));await nav('/ground/services');await shot('ground-ready','[data-testid="local-simulation"]');
 await p.evaluate(()=>{const a=window.__LOCAL_FLIGHT__;a.editFlight({...a.getState().flight,rampKg:30000});a.confirmFlight();window.__LOCAL_RUNTIME__.preset('parked');window.__LOCAL_RUNTIME__.command('refuel');});await p.waitForTimeout(500);await p.evaluate(()=>{const a=window.__LOCAL_FLIGHT__;a.editFlight({...a.getState().flight,rampKg:21257});a.confirmFlight();});await p.waitForFunction(()=>window.__LOCAL_RUNTIME__.snapshot().commands[0].status==='completed');await shot('ground-old-plan','[data-testid="command-receipt"]');await shot('ground-differences','[data-testid="ground-preparation"]',true);
 await nav('/failures');await p.getByRole('button',{name:'激活加油故障',exact:true}).click();await shot('fault','[data-testid="local-faults"]');
 await p.reload();await p.waitForFunction(()=>window.__LOCAL_FLIGHT__&&window.__EFB_NAVIGATE);await p.waitForTimeout(2800);await p.getByTestId('ground-reset-entry').click();await shot('refresh','[data-testid="local-presets"]');await p.getByRole('button',{name:'恢复准备预设',exact:true}).click();await shot('prepared','[data-testid="local-presets"]');
 await nav('/navigation/local-files');await shot('charts','[data-testid="offline-charts"]');await nav('/checklists');await shot('checklist','#instrument');await nav('/settings');await shot('settings','#instrument');await nav('/performance/top-of-descent');await shot('tod','#instrument');
 }
 for(const [id,step] of [['preflight',10],['change',2],['tools',5],['resources',6],['takeoff',3],['planning',5]]){
  await p.goto(base+'/demo.html?autoplay=0&scenario='+id);await p.waitForFunction(()=>window.__BID_PRESENTATION__&&!window.__BID_PRESENTATION__.status().busy,{},{timeout:45000});await p.evaluate(i=>window.__BID_PRESENTATION__.seek(i),step);await p.waitForFunction(()=>!window.__BID_PRESENTATION__.status().busy,{},{timeout:60000});await p.evaluate(()=>window.__BID_PRESENTATION__.pause());if(await p.evaluate(()=>window.__BID_PRESENTATION__.status().failed))throw Error(await p.locator('#error-text').innerText());await p.screenshot({path:path.join(out,'demo-'+id+'.png')});records.push({name:'demo-'+id,scenario:id,step,record:await p.evaluate(()=>window.__BID_PRESENTATION__.record())});
 }
 if(errors.length)throw Error(errors.join('; '));fs.writeFileSync(path.join(root,'演示/场景脚本.json'),JSON.stringify(await p.evaluate(()=>window.__BID_PRESENTATION__.scenarios),null,2));fs.writeFileSync(path.join(__dirname,'capture.json'),JSON.stringify({softwareVersion:'1.3.1',health:await(await fetch(base+'/__health')).json(),records,errors},null,2));console.log('Captured '+records.length+' program views');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
